version: 2
jobs:
  build:

    working_directory: ~/spring-boot-ng

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - run: mvn package -DskipTests dependency:go-offline

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run: mvn package

      - store_test_results:
          path: server/target/surefire-reports

      - store_artifacts:
          path: client/target/client-0.0.1-SNAPSHOT.jar